[programs.localnet]
scrt_escrow = "Hv4LktuBNs6T62X7LEkmqJZseGvVCxwCkAjqFq3pZqCb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/earth/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
